name: Update TryHackMe badge

on:
  schedule:
    - cron: "15 0 * * *"   # chạy mỗi ngày lúc 00:15 UTC (~07:15 VN)
  workflow_dispatch:       # cho phép chạy thủ công từ tab Actions

permissions:
  contents: write          # cần để commit/push bằng GITHUB_TOKEN

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download latest badge
        run: |
          mkdir -p assets
          # Đổi '1yn3r' thành username badge của bạn nếu khác
          curl -fsSL "https://tryhackme-badges.s3.amazonaws.com/1yn3r.png?ts=$(date +%s)" -o /tmp/thm.png

          # Nếu ảnh chưa tồn tại thì coi như khác để copy
          if [ ! -f assets/tryhackme.png ]; then
            cp /tmp/thm.png assets/tryhackme.png
            echo "NEW_FILE=1" >> $GITHUB_ENV
          else
            # So sánh; nếu khác thì cập nhật
            if ! cmp -s /tmp/thm.png assets/tryhackme.png; then
              cp /tmp/thm.png assets/tryhackme.png
              echo "NEW_FILE=1" >> $GITHUB_ENV
            else
              echo "NEW_FILE=0" >> $GITHUB_ENV
            fi
          fi

      - name: Commit & push if changed
        if: env.NEW_FILE == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/tryhackme.png
          git commit -m "chore: update TryHackMe badge"
          git push
